### ISSUE TITLE
Unable to cdk deploy as it throws the UnreservedConcurrentExecution error

### ISSUE THREAD

**Issue by gitmurali** [aws-samples/infrastructure-assessment-iac-automation#2]
After trying to deploy using `cdk deploy` I'm getting the following error..

`Specified ConcurrentExecutions for function decreases account's UnreservedConcurrentExecution below its minimum value of [10]
`
Could you please update your example by fixing this issue ? Thanks

**Comment by gwmanish** [comment]
lambda function have a reserved_concurrent_executions limit set to 20. This concurrency limit will reserve a portion of the account’s level concurrency limit for this function. This feature allows to throttle a given function if it reaches a maximum number of concurrent executions allowed. It is required to validate that the concurrent executions quota for AWS Lambda for each Region allows the needed reserved_concurrent_executions limit.

To request a Concurrent execution quota increase for AWS Lambda, complete the following steps:

1. Navigate to the [Service Quotas console](https://console.aws.amazon.com/servicequotas/home).

2. Select AWS Lambda.

3. Search and select Concurrent executions quota.

4. Choose Request quota increase.

5. Change quota value to desired one.

6. Choose Request.

For your reference : https://docs.aws.amazon.com/solutions/latest/audience-uploader-from-aws-clean-rooms/quotas-for-aws-services-in-this-solution.html
